# Don't print a new line at the start of the prompt
add_newline = false

[character]
symbol = "à§¸"
error_symbol = "âŠ—"
use_symbol_for_status = true

[directory]
truncation_length = 3
prefix = ""

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[git_state]
progress_divider = " of "

[git_status]
conflicted = " âš”ï¸"
ahead = " ğŸï¸  ğŸ’¨"
behind = " ğŸ¢"
diverged = "  ğŸ”±"
untracked = " ğŸ›¤ï¸"
stashed = " ğŸ“¦"
modified = " ğŸ“"
staged = " ğŸ—ƒï¸"
renamed = " ğŸ“›"
deleted = " ğŸ—‘ï¸"
prefix = ""
suffix = ""
style = "bright-white"

[package]
disabled = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
